// Ícono, color y descripción por sección (réplica del home de la vanilla).
export const META: Record<string, { ico: string; col: string; desc: string }> = {
  'estado-sistema': { ico: '🩺', col: '61,200,160', desc: 'Salud del backend, la base y las automatizaciones, y estado de los respaldos' },
  'delegaciones': { ico: '🔁', col: '92,104,128', desc: 'Delegá tus aprobaciones en otra persona por un período' },
  'fichadas-consulta': { ico: '🕘', col: '61,127,255', desc: 'Consultá y autorizá las fichadas por período' },
  'fichadas-dia': { ico: '📅', col: '61,127,255', desc: 'Fichadas del día en curso' },
  'fichadas-equipo': { ico: '👥', col: '61,127,255', desc: 'Fichadas de tu equipo para autorizar' },
  'fichadas-import': { ico: '📥', col: '61,127,255', desc: 'Importación de fichadas desde el reloj/Pro-Soft' },
  'mis-delegaciones': { ico: '🔁', col: '92,104,128', desc: 'Aprobaciones que te delegaron temporalmente' },
  'mis-fichadas': { ico: '🕘', col: '61,200,160', desc: 'Tus fichadas del día' },
  'aprobaciones-pendientes': { ico: '✅', col: '61,127,255', desc: 'Todo lo que espera tu aprobación (adelantos, licencias y sanciones) en un solo lugar' },
  'mis-recibos': { ico: '📄', col: '61,200,160', desc: 'Consultá y descargá tus recibos de haberes' },
  'mis-ganancias': { ico: '🧾', col: '234,179,8', desc: 'Consultá tu cálculo del Impuesto a las Ganancias (F.1357)' },
  'mis-datos': { ico: '👤', col: '92,104,128', desc: 'Tu información personal y laboral' },
  'turnos-reglas': { ico: '🕒', col: '217,119,6', desc: 'Jornada, horario de ingreso y regla de cada turno (recorte de entrada anticipada)' },
  'seguridad': { ico: '🔐', col: '92,104,128', desc: 'Verificación en dos pasos (2FA) de tu cuenta' },
  'anticipos': { ico: '💸', col: '61,127,255', desc: 'Solicitá un adelanto de tu sueldo' },
  'mis-licencias': { ico: '🏖', col: '34,197,94', desc: 'Solicitá y consultá tus licencias y vacaciones' },
  'justificar-licencia': { ico: '📎', col: '168,85,247', desc: 'Presentá el comprobante que justifica tu licencia' },
  'mensajes': { ico: '💬', col: '61,127,255', desc: 'Enviá una consulta o mensaje a Recursos Humanos' },
  'mis-cbus': { ico: '🏦', col: '61,200,160', desc: 'Cargá tus cuentas y el porcentaje de acreditación' },
  'cert-trabajo': { ico: '📋', col: '99,102,241', desc: 'Solicitá tu certificado laboral firmado' },
  'mis-sanciones': { ico: '⚖️', col: '239,68,68', desc: 'Consultá tus sanciones y notificaciones' },
  'mis-evaluaciones': { ico: '📈', col: '94,194,255', desc: 'Consultá tus evaluaciones de desempeño' },
  'mi-formacion': { ico: '🎓', col: '94,194,255', desc: 'Tus cursos asignados: contenidos y avance de cada uno' },
  'mi-feedback': { ico: '💬', col: '94,194,255', desc: 'Respondé las evaluaciones de feedback 360° que te asignaron' },
  'asistente-ia': { ico: '🤖', col: '168,85,247', desc: 'Resúmenes de encuestas/feedback, borradores y asistente con IA (opcional)' },
  'sicore-ganancias': { ico: '🧾', col: '234,179,8', desc: 'Retenciones y devoluciones de Ganancias 4ª para informar a ARCA (SICORE, rég. 602)' },
  'matriz-antiguedad': { ico: '📐', col: '61,127,255', desc: 'Fija el sueldo básico por tramos de antigüedad (por convenio/categoría o global)' },
  'modalidades': { ico: '📑', col: '92,104,128', desc: 'Modalidades de contratación: prueba, indemnización, SAC y código AFIP' },
  'competencias': { ico: '🧭', col: '94,194,255', desc: 'Catálogo central de competencias para desempeño y feedback 360' },
  'unidades': { ico: '🏢', col: '61,127,255', desc: 'Estructura organizativa: árbol de unidades y organigrama' },
  'posiciones': { ico: '🪑', col: '61,127,255', desc: 'Posiciones con dotación planificada, ocupadas y vacantes' },
  'workflows': { ico: '🔀', col: '92,104,128', desc: 'Flujos de aprobación configurables por proceso' },
  'mis-familiares': { ico: '👨‍👩‍👧', col: '94,194,255', desc: 'Cargá y gestioná tu grupo familiar' },
  'tablero-equipo': { ico: '📊', col: '61,127,255', desc: 'Indicadores de tu equipo: costo, asistencia, horas extra, pendientes y avisos' },
  'aprobaciones': { ico: '✅', col: '34,197,94', desc: 'Recomendá adelantos de tu equipo (RR.HH. resuelve)' },
  'licencias-equipo': { ico: '🏖', col: '34,197,94', desc: 'Licencias y vacaciones de tu equipo' },
  'organigrama': { ico: '🗂', col: '61,127,255', desc: 'Estructura y personas a cargo' },
  'puestos': { ico: '🧩', col: '61,127,255', desc: 'Estructura por puesto: quién reporta a quién y ocupantes de cada puesto' },
  'descripcion-puestos': { ico: '📝', col: '61,127,255', desc: 'Perfil de cada puesto: misión, funciones, requisitos y competencias' },
  'costo-equipo': { ico: '💰', col: '34,197,94', desc: 'Costo laboral de tus empleados a cargo' },
  'datos-equipo': { ico: '🪪', col: '61,127,255', desc: 'Datos personales y de contacto de tu equipo' },
  // Comité de Higiene y Seguridad
  'chs-politica': { ico: '📜', col: '37,99,235', desc: 'Política vigente de Higiene y Seguridad y su difusión' },
  'chs-capacitaciones': { ico: '🎓', col: '234,179,8', desc: 'Plan Anual de Capacitaciones (PAC) y seguimiento' },
  'chs-siniestros': { ico: '🚑', col: '239,68,68', desc: 'Siniestros: ART, accidentes, enfermedades e incidentes' },
  'chs-auditorias': { ico: '🔍', col: '99,102,241', desc: 'Auditorías e inspecciones y sus acciones correctivas' },
  'chs-epp': { ico: '🦺', col: '245,158,11', desc: 'Matriz de EPP por puesto y registro de entregas' },
  'chs-riesgos': { ico: '⚠️', col: '239,68,68', desc: 'Procesos y matriz de riesgos por tarea' },
  'chs-carteleria': { ico: '🪧', col: '61,127,255', desc: 'Cartelería de seguridad instalada y su estado' },
  'chs-minutas': { ico: '🗒', col: '92,104,128', desc: 'Minutas de las reuniones del Comité de HyS' },
  'chs-noconf': { ico: '🧯', col: '245,158,11', desc: 'No conformidades y oportunidades de mejora' },
  'chs-mediciones': { ico: '📐', col: '34,197,94', desc: 'Mediciones obligatorias y control de vencimientos' },
  'chs-evidencias': { ico: '📸', col: '34,197,94', desc: 'Evidencias de mejoras implementadas' },
  'chs-dashboard': { ico: '📊', col: '94,194,255', desc: 'Indicadores del Comité de HyS' },
  'sanciones-equipo': { ico: '⚖️', col: '239,68,68', desc: 'Solicitá y seguí sanciones de tu equipo' },
  'evaluaciones-equipo': { ico: '📈', col: '94,194,255', desc: 'Evaluá el desempeño de tu equipo' },
  // RR.HH.
  'personas': { ico: '🧑‍🤝‍🧑', col: '99,102,241', desc: 'Base de personas: empleados, familiares, prestadores, postulantes y sus períodos' },
  'reclutamiento': { ico: '🎯', col: '99,102,241', desc: 'Búsquedas y candidatos: postulado → entrevista → oferta → contratado' },
  'empleados': { ico: '👥', col: '61,127,255', desc: 'Alta, baja y modificación de empleados' },
  'actualizacion-masiva': { ico: '🗂️', col: '61,127,255', desc: 'Cambiá un mismo dato (obra social, convenio, sindicato, categoría, lugar…) a varios legajos a la vez' },
  'plantillas-legajo': { ico: '🧾', col: '61,127,255', desc: 'Moldes con valores por defecto para dar de alta empleados más rápido' },
  'agrupaciones': { ico: '🏷️', col: '61,127,255', desc: 'Grupos libres de legajos (proyecto, sector, turno) para filtrar el listado' },
  'adelantos-rrhh': { ico: '💸', col: '61,127,255', desc: 'Otorgá/rechazá adelantos y definí las cuotas' },
  'liquidacion': { ico: '🧮', col: '61,200,160', desc: 'Liquidá haberes por tipo y corrida' },
  'controles-liq': { ico: '✅', col: '239,68,68', desc: 'Controles previos al cierre: netos negativos, aportes, tope SIPA, variaciones y faltantes' },
  'novedades': { ico: '📝', col: '61,127,255', desc: 'Novedades variables del período (horas extra, ausencias, premios) que alimentan la liquidación' },
  'recibos-gestion': { ico: '📄', col: '61,200,160', desc: 'Generá, publicá y auditá recibos' },
  'ganancias-rrhh': { ico: '🧾', col: '234,179,8', desc: 'Impuesto a las Ganancias y F.1357' },
  'ganancias-params': { ico: '⚙️', col: '234,179,8', desc: 'Tablas y parámetros del Impuesto a las Ganancias' },
  'liquidacion-anual': { ico: '📅', col: '234,179,8', desc: 'Liquidación anual del Impuesto a las Ganancias' },
  'escalas': { ico: '📊', col: '99,102,241', desc: 'Escalas salariales y convenios por sindicato' },
  'conceptos': { ico: '🧩', col: '92,104,128', desc: 'Conceptos de haberes y descuentos' },
  'sanciones': { ico: '⚖️', col: '239,68,68', desc: 'Gestioná sanciones disciplinarias' },
  'evaluaciones': { ico: '📈', col: '94,194,255', desc: 'Evaluaciones de desempeño del personal' },
  'desempeno-9box': { ico: '🎯', col: '94,194,255', desc: 'Objetivos, competencias y matriz potencial vs. desempeño (9-box)' },
  'tablero-talento': { ico: '📈', col: '94,194,255', desc: 'Rotación, ausentismo, dotación y antigüedad del personal (analítica de talento)' },
  'compensaciones': { ico: '💰', col: '61,200,160', desc: 'Bandas salariales por puesto y análisis de compa-ratio (posición vs banda)' },
  'seleccion-embudo': { ico: '🧲', col: '168,85,247', desc: 'Embudo de selección, origen y evaluación por criterios de candidatos' },
  'lms': { ico: '🎓', col: '94,194,255', desc: 'Contenidos/lecciones de cada curso e itinerarios de aprendizaje' },
  'desarrollo': { ico: '🎯', col: '94,194,255', desc: 'OKRs (objetivos y resultados clave) y evaluaciones de feedback 360°' },
  'muro': { ico: '📣', col: '168,85,247', desc: 'Comunicados de la empresa y reconocimientos entre compañeros' },
  'comunicados-rrhh': { ico: '📣', col: '168,85,247', desc: 'Publicar comunicados, ver acuses y ranking de reconocimientos' },
  'fichar-web': { ico: '📲', col: '61,200,160', desc: 'Registrá tu entrada y salida desde el navegador o el celular, con ubicación' },
  'fichaje-web': { ico: '📲', col: '61,127,255', desc: 'Consulta de fichajes web (self check-in), independiente del reloj Pro-Soft' },
  'mis-firmas': { ico: '✍️', col: '234,179,8', desc: 'Documentos (contratos, políticas) que tenés que leer y firmar' },
  'documentos-firma': { ico: '✍️', col: '234,179,8', desc: 'Distribuir documentos para firma del empleado y seguir los acuses' },
  'onboarding': { ico: '🚀', col: '34,197,94', desc: 'Checklist de tareas de alta por empleado y su plantilla' },
  'formacion': { ico: '🎓', col: '234,179,8', desc: 'Catálogo de cursos e inscripciones: estado, calificación y horas' },
  'sucesion': { ico: '🪜', col: '99,102,241', desc: 'Sucesores posibles por puesto y su grado de preparación' },
  'simulaciones': { ico: '🔮', col: '168,85,247', desc: 'Simulá liquidaciones, finales y gratificaciones' },
  'simulador-ganancias': { ico: '🧮', col: '234,179,8', desc: 'Proyección anual de retención de Ganancias (RG 4003)' },
  'siradig': { ico: '📥', col: '234,179,8', desc: 'Importá el SiRADIG (F.572) y mirá las deducciones declaradas por cada empleado' },
  'ganancias-control': { ico: '📋', col: '234,179,8', desc: 'Control consolidado de Ganancias por empleado: gravado, deducciones, retención' },
  'ganancias-apertura': { ico: '🟰', col: '234,179,8', desc: 'Carga inicial de acumulados de Ganancias (arranque a mitad de año / otro empleador)' },
  'tablero': { ico: '📊', col: '61,127,255', desc: 'Indicadores de RR.HH.: headcount, masa salarial, costo laboral, ausentismo' },
  'ganancias-final': { ico: '📅', col: '234,179,8', desc: 'Liquidación final anual de Ganancias (RG 4003): impuesto anual vs. retenido' },
  'embargos': { ico: '⚖️', col: '239,68,68', desc: 'Embargos judiciales y cuota alimentaria, con topes de embargabilidad' },
  'provision': { ico: '🧾', col: '92,104,128', desc: 'Provisión mensual devengada de SAC y vacaciones (para el asiento)' },
  'alertas': { ico: '🔔', col: '245,158,11', desc: 'Vencimientos: ART, mediciones HyS, período de prueba, contratos' },
  'acumuladores': { ico: '🧮', col: '99,102,241', desc: 'Acumuladores configurables (remunerativo, neto, aportes, retención) y su consulta por período' },
  'valores-aux': { ico: '🧷', col: '99,102,241', desc: 'Macros, matrices por tramos y tablas usables en las fórmulas de conceptos' },
  'licencias-rrhh': { ico: '🏖', col: '34,197,94', desc: 'Gestión y justificación de licencias' },
  'vacaciones': { ico: '🌴', col: '34,197,94', desc: 'Saldos de vacaciones por antigüedad (LCT art. 150) y programación del goce' },
  'legajo-docs': { ico: '🗂', col: '99,102,241', desc: 'Documentación del legajo con control de vencimientos (DNI, exámenes, matrículas)' },
  'hys': { ico: '🦺', col: '245,158,11', desc: 'Higiene y Seguridad en el trabajo' },
  'mis-hys': { ico: '🦺', col: '234,179,8', desc: 'Mis capacitaciones, EPP, talles y manuales de seguridad' },
  'beneficios': { ico: '🎁', col: '34,197,94', desc: 'Beneficios del personal' },
  'elementos-trabajo': { ico: '🧰', col: '92,104,128', desc: 'Elementos y herramientas entregadas' },
  'reportes': { ico: '📑', col: '61,127,255', desc: 'Generador de reportes multi-dataset' },
  'encuestas-rrhh': { ico: '📊', col: '168,85,247', desc: 'Encuestas de clima: preguntas, apertura y resultados agregados' },
  'mis-encuestas': { ico: '🗳️', col: '168,85,247', desc: 'Respondé las encuestas de clima disponibles' },
  'f931': { ico: '🏛', col: '234,179,8', desc: 'Declaración jurada F.931 (AFIP)' },
  'libro-sueldos': { ico: '📚', col: '99,102,241', desc: 'Libro de sueldos (art. 52 LCT)' },
  'asiento': { ico: '🧾', col: '92,104,128', desc: 'Asiento contable de la liquidación' },
  'bancos': { ico: '🏦', col: '61,200,160', desc: 'Archivos de acreditación bancaria' },
  'cbu-novedades': { ico: '🏦', col: '61,200,160', desc: 'Novedades y validación de CBU' },
  'ddjj-sindical': { ico: '🤝', col: '168,85,247', desc: 'Declaración jurada de aportes sindicales' },
  'simplificacion': { ico: '🏛', col: '234,179,8', desc: 'Altas y bajas de personal del período para AFIP/ARCA (Simplificación Registral)' },
  'documentos': { ico: '✍️', col: '99,102,241', desc: 'Documentos firmados por el personal' },
  'cert-trabajo-rrhh': { ico: '📋', col: '99,102,241', desc: 'Emisión de certificados de trabajo' },
  'cert-servicios': { ico: '📃', col: '99,102,241', desc: 'Certificación de servicios y remuneraciones (ANSES PS.6.2) para el egreso' },
  'mensajes-rrhh': { ico: '💬', col: '61,127,255', desc: 'Mensajes y consultas de empleados' },
  'cambios-domicilio': { ico: '🏠', col: '92,104,128', desc: 'Cambios de domicilio del personal' },
  'art-empresas': { ico: '🛡', col: '245,158,11', desc: 'Contratos de ART por empresa' },
  'sindicatos': { ico: '🤝', col: '168,85,247', desc: 'Sindicatos y convenios colectivos' },
  'reglamento': { ico: '📜', col: '92,104,128', desc: 'Reglamento y licencias especiales' },
  'campos-adicionales': { ico: '🏷️', col: '99,102,241', desc: 'Definí campos propios del legajo (talles, matrículas, etc.) para el ABM de Empleados' },
  'modelo-recibo': { ico: '🧾', col: '92,104,128', desc: 'Encabezado, leyenda al pie y logo del recibo de haberes' },
  'cierre-periodos': { ico: '🔒', col: '239,68,68', desc: 'Cierre de períodos de liquidación' },
  'valores-legales': { ico: '🏛', col: '239,68,68', desc: 'Tope SIPA, SMVM, Seguro de Vida Obligatorio y FFEP versionados por vigencia (se verifican antes de cada corrida)' },
  // Administración
  'admin-empresas': { ico: '🏢', col: '61,127,255', desc: 'Gestión de empresas del grupo' },
  'centros-operaciones': { ico: '📍', col: '61,127,255', desc: 'Locaciones donde operan las empresas; se vinculan a una o varias empresas' },
  'admin-usuarios': { ico: '👤', col: '61,127,255', desc: 'Usuarios y accesos al sistema' },
  'user-levels': { ico: '🔑', col: '168,85,247', desc: 'Niveles y permisos de usuario' },
  'auditoria': { ico: '🔍', col: '92,104,128', desc: 'Registro de auditoría del sistema' },
  'parametros': { ico: '⚙️', col: '92,104,128', desc: 'Parámetros generales de liquidación' },
  'parametros-hist': { ico: '🗃', col: '92,104,128', desc: 'Versiones de parámetros por vigencia para reliquidar meses anteriores' },
};
export const fallback = { ico: '▸', col: '92,104,128', desc: '' };
